[workspace]
resolver = "2"
members = [
    "brec_macros",
    "brec"
]
exclude = [
    "gen_tests/*"
]

[workspace.dependencies]
thiserror = "2.0"
uuid = "1.8"
proptest = "1.4"
paste = "1.0"
syn = { version  = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
enum_ids = "0.7"
crc32fast = "1.4"
lazy_static = "1.5"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
brec_macros = { version = "0.2", path = "./brec_macros" }
fs4 = { version = "0.13", features = ["sync"] }