use crate::*;
use std::fmt;

pub struct FileHeader {
    file_name: String,
    package: String,
}

impl FileHeader {
    pub fn new(file_name: impl Into<String>, package: impl Into<String>) -> Self {
        Self {
            file_name: file_name.into(),
            package: package.into(),
        }
    }
}

impl FormatterWritable for FileHeader {
    fn write(&self, writer: &mut FormatterWriter) -> fmt::Result {
        writer.ln(format!(
            "// Generated by brec-node-types. Do not edit by hand."
        ))?;
        writer.ln(format!("// Source package: {}", self.package))?;
        writer.ln(format!("// File: {}", self.file_name))
    }
}
