[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
brec = { path = "../../brec", features=["bincode"]  }
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
brec = { path = "../../brec", features=["build"] }
