[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
brec = { workspace = true, features=["bincode"]  }
rand.workspace = true
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
brec = { workspace = true, features=["build"] }
