mod names;

use std::fs;
use std::path::{Path, PathBuf};

use crate::{Error, error::SCHEME_FILE_NAME};
use brec_scheme::SchemeFile;
use names::TypeNames;

/// Normalized view of `brec.scheme.json` used by every generator backend.
///
/// Java generation mostly consumes the raw scheme directly, but `Model` keeps
/// the shared package metadata and validates that named payload references were
/// exported into the scheme with `#[payload(include)]`.
pub struct Model {
    scheme_path: PathBuf,
    pub version: String,
    pub package: String,
}

impl TryFrom<Option<PathBuf>> for Model {
    type Error = Error;

    fn try_from(value: Option<PathBuf>) -> Result<Self, Self::Error> {
        let scheme_path = match value {
            Some(path) => path,
            None => find_scheme_path(&std::env::current_dir()?)?,
        };
        let content = fs::read_to_string(&scheme_path)?;
        let scheme: SchemeFile = serde_json::from_str(&content)?;
        Self::from_scheme_file(scheme_path, &scheme)
    }
}

impl Model {
    pub fn scheme_path(&self) -> &Path {
        &self.scheme_path
    }

    pub fn scheme_parent_path(&self) -> Result<&Path, Error> {
        self.scheme_path
            .parent()
            .ok_or_else(|| Error::MissingParent(self.scheme_path.clone()))
    }

    fn from_scheme_file(scheme_path: PathBuf, scheme: &SchemeFile) -> Result<Self, Error> {
        TypeNames::try_from(scheme)?;

        Ok(Self {
            scheme_path,
            version: scheme.version.clone(),
            package: scheme.package.clone(),
        })
    }
}

impl TryFrom<&SchemeFile> for Model {
    type Error = Error;

    fn try_from(scheme: &SchemeFile) -> Result<Self, Self::Error> {
        Self::from_scheme_file(PathBuf::new(), scheme)
    }
}

/// Locates the scheme generated by `brec::generate!(scheme)`.
///
/// The fast path mirrors the normal Cargo layout. The recursive fallback keeps
/// the CLI usable from hand-built examples where the scheme was copied next to
/// protocol sources or another output directory.
fn find_scheme_path(start: &Path) -> Result<PathBuf, Error> {
    let direct = start.join("target").join(SCHEME_FILE_NAME);
    if direct.is_file() {
        return Ok(direct);
    }

    let mut dirs = vec![start.to_path_buf()];
    let mut matches = Vec::new();

    while let Some(dir) = dirs.pop() {
        for entry in fs::read_dir(&dir)? {
            let entry = entry?;
            let path = entry.path();
            let fty = entry.file_type()?;
            if fty.is_dir() {
                dirs.push(path);
                continue;
            }
            if fty.is_file()
                && path
                    .file_name()
                    .is_some_and(|name| name == SCHEME_FILE_NAME)
            {
                matches.push(path);
            }
        }
    }

    match matches.len() {
        0 => Err(Error::SchemeNotFound(start.to_path_buf())),
        1 => Ok(matches.remove(0)),
        _ => Err(Error::MultipleSchemes(matches)),
    }
}
