use crate::*;

/// Standard header placed at the top of generated source files.
///
/// It records both the generator version and the source protocol package so
/// stale generated files are easy to identify during debugging.
pub struct FileHeader<'a> {
    file_name: String,
    model: &'a Model,
}

impl<'a> FileHeader<'a> {
    pub fn new(file_name: impl Into<String>, model: &'a Model) -> Self {
        Self {
            file_name: file_name.into(),
            model,
        }
    }
}

impl<'a> SourceWritable for FileHeader<'a> {
    fn write(&self, writer: &mut SourceWriter) -> Result<(), Error> {
        writer.ln(format!(
            "// Generated by {} {}. Do not edit by hand.",
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION"),
        ))?;
        writer.ln(format!(
            "// Source package: {} {}",
            self.model.package, self.model.version
        ))?;
        writer.ln(format!("// File: {}", self.file_name))
    }
}
