#!/bin/bash
set -e

cd ./runner
BREC_TEST_MEASUREMENTS_ITERATIONS=1 \
BREC_TEST_MEASUREMENTS_ITERATIONS_CRYPT=1 \
BREC_TEST_MEASUREMENTS_PACKAGES=10 \
BREC_TEST_MEASUREMENTS_RECORDS=100 \
cargo test --release -- --nocapture

cd ..
