#!/bin/bash
set -e

BREC_TEST_MEASUREMENTS_ITERATIONS=10 \
BREC_TEST_MEASUREMENTS_ITERATIONS_CRYPT=10 \
BREC_TEST_MEASUREMENTS_PACKAGES=100 \
BREC_TEST_MEASUREMENTS_RECORDS=10000 \
cargo test --release -- --nocapture

