#!/bin/bash
set -e

BREC_TEST_MEASUREMENTS_ITERATIONS=10 \
BREC_TEST_MEASUREMENTS_ITERATIONS_CRYPT=10 \
BREC_TEST_MEASUREMENTS_PACKAGES=100 \
BREC_TEST_MEASUREMENTS_RECORDS=10000 \
BREC_SESSION_REUSE_LIMIT=1 \
BREC_DECRYPT_CACHE_LIMIT=1 \
cargo test --release -- --nocapture

