[package]
name = "brec"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "macros/packet",
    "macros/include",
    "."
]

[features]
build = []

[dependencies]
thiserror.workspace = true
crc32fast.workspace = true
packet = { path = "./macros/packet"}
include = { path = "./macros/include"}

[workspace.dependencies]
thiserror = "2.0"
uuid = "1.8"
proptest = "1.4"
paste = "1.0"
syn = {version  = "2.0", features = ["full"]}
quote = "1.0"
proc-macro2 = "1.0"
enum_ids = "0.6"
crc32fast = "1.4"
lazy_static = "1.5"