use super::project_file::namespace_name;
use crate::*;

pub struct GeneratedFile<'a> {
    pub model: &'a Model,
    pub file_name: &'static str,
}

impl GeneratedFile<'_> {
    pub fn write_header(&self, writer: &mut SourceWriter) -> Result<(), Error> {
        writer.ln(format!(
            "// Generated by {} {}. Do not edit by hand.",
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION"),
        ))?;
        writer.ln(format!(
            "// Source package: {} {}",
            self.model.package, self.model.version
        ))?;
        writer.ln(format!("// File: {}", self.file_name))
    }

    pub fn write_namespace(&self, writer: &mut SourceWriter) -> Result<(), Error> {
        writer.ln(format!(
            "namespace {};",
            namespace_name(&self.model.package)
        ))
    }
}
