name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchains
        run: |
          rustup update
          rustup install nightly
          rustup component add clippy --toolchain nightly
      - name: Make scripts executable
        run: chmod +x ./lint.sh
      - name: Linting nightly
        run: sh ./lint.sh

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update rust
        run: rustup update
      - name: Make scripts executable
        run: chmod +x ./test.sh
      - name: Tests
        run: sh ./test.sh
